<?php require('template/header.phtml'); ?>

    <input type="hidden" value="<?php echo $_SESSION['userID']; ?>" id="userID">
    <div class="container">

        <div class="col-lg-offset-0">

            <div id="myList">

                <form action="<?php
                echo $_SERVER['PHP_SELF'];
                ?>" method="post">
                    <?php
                    if (empty($view->basket) and !(isset($_GET['thankYou']))) {
                        echo '<p  style="text-align: center; font-size: 20px;">
                            Your basket is empty. Feel free to <a style="color: #2b669a" href="../shopList.php">
                            <b>check</b></a> out our latest offers!
                          </p>';

                    } else {

                        echo '

                        <nav class="nav navbar-fixed">

                        <div class="col-xs-12">
                            <button class="clearCart btn btn-danger">Clear Cart</button>
                            <input type="submit" class="btn btn-success pull-right" name="checkOut" value="CheckOut">

                        </div>
                        </nav>';

                        $totalPrice = 0; // variable for price
                        $finalPrice = 0;
                        foreach ($view->basket as $basketData) {

                            $basketBookId = $basketData->getBookID();
                            $book         = $view->booksDataSet->searchBook('idBook', $basketBookId);
                            $totalPrice += ($basketData->getQuantity() * $book->getPrice());
                            $finalPrice += $totalPrice;

                            echo '
                <div id="bookSet' . $basketData->getBookID() . '" class="bookSet col-sm-12" data-id="' . $basketData->getIdBasket() . '">
                        <p>' . '<img src="../images/' . $book->getPhotoName() . ' " alt="no pic" />' . '</p>
                        <p><b>Name:</b> ' . $book->getBookName() . ' </p>
                        <p><b>Available: </b>' . $book->getNumberInStock() . ' </p>
                        <p><b>Price: £</b>' . $book->getPrice() . ' </p>
                        <p><b>Total price: £</b>' . ($basketData->getQuantity() * $book->getPrice()) . '</p>
                        <p><b>Quantity:</b>
                        <a style="color: green;" class="removeFromCartMinus glyphicon glyphicon-minus-sign" data-quantity="itemQuantity' . $basketData->getBookID() . '" data-id=" ' . $basketData->getBookID() . '">
                        <span id="itemQuantity' . $basketData->getBookID() . '" > ' . $basketData->getQuantity() . '</span> </a>
                         <a style="color: green;" class="addToCartPlus glyphicon glyphicon-plus-sign" data-quantity="itemQuantity' . $basketData->getBookID() . '" data-id=" ' . $basketData->getBookID() . ' "></a>
                         </p>
                      <p>' . '<button data-id="' . $basketData->getIdBasket() . '" class="removeFromCart"><b>Remove</b><span class="glyphicon glyphicon-shopping-cart"></span></button>' . ' </p>
                </div> ';
                        }

                        //                echo '<p><b>Total price £: </b>' . $finalPrice . ' </p>';
                    }

                    if (isset($_GET['thankYou'])) {

                        echo '<h3 class="text-center text-success">Thank you for shopping with us!</h3>';
                    }

                    ?>

                </form>

            </div>
        </div>
    </div>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>

    <div class="container">
        <div class="row">
            <div id="myList" class="col-md-10 col-md-offset-1">
<?php
if (empty($view->basket) and !(isset($_GET['thankYou']))) {
    echo '<p  style="text-align: center; font-size: 20px;">
                         Your basket is empty. Feel free to <a style="color: #2b669a" href="../shopList.php">
                           <b>check</b></a> out our latest offers!                                                  
                      </p>';
} else {
    echo '<h1 class="panel-heading">Your Orders</h1>
                <div class="panel panel-default panel-table">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col col-xs-6">
                                <button type="button" class="btn btn-block btn-danger btn-create">Clear Basket</button>
                        </div>
                        <div class="col col-xs-6 text-right">
                            <button type="button" class="btn btn-block btn-primary btn-create">Checkout</button>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <table class="table table-striped table-bordered table-list">
                        <thead>
                        <tr>
                            <th>Book Name</th>
                            <th>Quantity</th>
                            <th><em class="fa fa-cog"></em></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>';
    $totalPrice = 0; // variable for price
    $finalPrice = 0;

    $pages = ceil(count($view->basketDataSet->fetchAllBasket($_SESSION['userID'])) / $limit);

    foreach ($view->basket as $basketData) {

        $basketBookId = $basketData->getBookID();
        $book         = $view->booksDataSet->searchBook('idBook', $basketBookId);
        $totalPrice += ($basketData->getQuantity() * $book->getPrice());
        $finalPrice += $totalPrice;
        echo '
            <td id="bookSet' . $basketData->getBookID() . '" class="hidden col-sm-12"
                data-id="' . $basketData->getIdBasket() . '">
            <td>' . $book->getBookName() . '</td>
            <td> ' . $basketData->getQuantity() . '</td>
            </td>
            <td align="center">
                <a class="btn btn-lg btn-primary"><em class="glyphicon glyphicon-plus-sign"></em></a>
                <a class="btn btn-lg btn-primary"><em class="glyphicon glyphicon-minus-sign"></em></a>
                <a class="btn btn-lg btn-danger"><em class="glyphicon glyphicon-remove"></em></a>
            </td>
            </tr>';
    }
    echo '</tbody>
            </table>
            <b> Total price £: ' . $totalPrice . ' </b>
                </div>
            <div class="panel-footer">
                <div class="row">';

    if (!isset($_GET['page'])) {
        $page = 1;
    } else {
        $page = $_GET['page'];
    }
    echo '<div class="hidden-xs col col-xs-4">Page ' . $page . ' of ' . $pages . '</div>
                                  <div class="col col-xs-8">
                                      <ul class="pagination hidden-xs pull-right">';
    for ($i = 1; $i <= $pages; $i++) {

        echo '<li><a href="' . $_SERVER['PHP_SELF'] . '?&page=' . $i . '">' . $i . '</a></li>';
    }
    echo '</ul>';
    echo '<ul class="pagination visible-xs pull-right">';
    if ($page > 1) {
        $previous = $page - 1;
        echo '<li><li><a href="' . $_SERVER['PHP_SELF'] . '?&page=' . $previous . '">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a></li>';
    }
    if ($page < 3) {
        $next = $page + 1;
        echo '<li><li><a href="' . $_SERVER['PHP_SELF'] . '?&page=' . $next . '">
                                       <span aria-hidden="true">&raquo;</span>
                                   </a></li>';
    }
    ;

    echo '</ul></div></div>';
    if (isset($_GET['thankYou'])) {

        echo '<h3 class="text-center text-success">Thank you for shopping with us!</h3>';
    }
}
