<?php require('template/header.phtml'); ?>

    <input type="hidden" value="<?php echo $_SESSION['userID']; ?>" id="userID">
    <input type="hidden" id="nrOfBooks" value="<?php echo $view->noOfBooks; ?>">

    <div class="container" id="shop">
        <div class="row">
            <div id="displayCartOperations"></div>
            <div id="myList" class="col-md-10 col-md-offset-1">
<?php
if (empty($view->basket) and !(isset($_GET['thankYou']))) {
    echo '<p  style="text-align: center; font-size: 20px;">
                         Your basket is empty. Feel free to <a style="color: #2b669a" href="../shopList.php">
                           <b>check</b></a> out our latest offers!                                                  
                      </p>';
} else if(isset($_GET['thankYou'])){
    echo '<h3 class="text-center text-success">Thank you for shopping with us!</h3>';
}
else {
    echo '<h1 class="panel-heading">Your Orders</h1>
        <form method="post" onclick="">
                <div class="panel panel-default panel-table">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col col-xs-6">
                                <button type="button" class="btn btn-block btn-danger btn-clear" 
                                onclick="removeAllItems()">Clear Basket</button>
                        </div>
                        <div class="col col-xs-6 text-right">
                            <button type="button" class="btn btn-block btn-primary btn-checkout"
                             onclick="checkOut();">Checkout</button>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <table class="table table-striped table-bordered table-list">
                        <thead>
                        <tr>
                           
                            <th class="hidden-xs">Book Image</th>
                            <th>Book Name</th>
                            <th>Number in Stock</th>
                            <th class="hidden-xs">Item Price</th>
                            <th class="hidden-xs">Quantity</th>
                            <th>Total Price</th>
                            <th style="text-align: right;"><em class=" fa fa-cog"></em></th>
                        </tr>
                        </thead>
                        <tbody>
                        <div id="displayBookMessage"></div>
                        ';
    $totalPrice = 0; // variable for price
    $finalPrice = 0;

    $pages = ceil(count($view->basketDataSet->fetchAllBasket($_SESSION['userID'])) / $limit);
    $i=0;
    setlocale(LC_MONETARY, 'en_GB');
    foreach ($view->basket as $basketData) {
        $basketBookId = $basketData->getBookID();
        $book         = $view->booksDataSet->searchBook('idBook', $basketBookId);
        $totalPrice += $basketData->getQuantity() * $book->getPrice();

        echo '
            <tr id="bookSets' . $basketData->getBookID() . '">
           <div id="bookSet' . $basketData->getBookID() . '" class="col-sm-12"
                data-id="' . $basketData->getIdBasket() . '">  
            <td class="hidden-xs"><p  style="text-align: center;">'.'<img id="smallImg"
            src="/images/' . $book->getPhotoName() . ' " alt="no pic" />' . '</p></td>   
            <td  style="text-align:center;">' . $book->getBookName() . '</td>
            <td>' . $book->getNumberInStock() . ' </td>
            <td  class="hidden-xs" id="priceForItem' . $basketData->getBookID() . '">' . money_format("%n",$book->getPrice()) . '</td>
            <td  class="hidden-xs" id="itemQuantity' . $basketData->getBookID() . '">' . $basketData->getQuantity() . '</td>
            <td><p class="remove" id="totalPriceForItem' . $basketData->getBookID() . '">' .
            money_format("%n", number_format($totalPrice,2)) . ' </p></td>
            </td>
            <td id="remove" align="center">
                <a id="remove" class="btn btn-lg btn-primary" style="margin: 5px;" onclick=addCartPlus("' . $basketData->getBookID() . '")>
                <em class="glyphicon glyphicon-plus-sign"></em></a>
                <a id="remove" class="btn btn-lg btn-primary" style="margin: 5px;" onclick=removeFromCartMinus("'. $basketData->getIdBasket() .'","' .
            $basketData->getBookID() . '","' . $basketData->getQuantity() . '")>
                <em class="glyphicon glyphicon-minus-sign"></em></a>
                <a id="remove" class="btn btn-lg btn-danger" style="margin: 5px;" onclick=removeFromCart("' . $basketData->getIdBasket() . '","'
            . $basketData->getBookID(). '")><em class="glyphicon glyphicon-remove"></em></a>
            </td>
        </div>
    </tr>'
           ;
        $finalPrice += $totalPrice;
        $totalPrice = 0;
    }

    echo '</tbody>
            </table>     
            
                </div>
            <div class="panel-footer">
                <div class="row">';

    if (!isset($_GET['page'])) {
        $page = 1;
    } else {
        $page = $_GET['page'];
    }
    echo '<div class="hidden-xs col col-xs-4">Page ' . $page . ' of ' . $pages . '</div>
                                  <div class="col col-xs-8">
                                      <ul class="pagination hidden-xs pull-right">';
    for ($i = 1; $i <= $pages; $i++) {

        echo '<li><a href="' . $_SERVER['PHP_SELF'] . '?&page=' . $i . '">' . $i . '</a></li>';
    }
    echo '</ul>';
    echo '<ul class="pagination visible-xs pull-right">';
    if ($page > 1) {
        $previous = $page - 1;
        echo '<li><li><a href="' . $_SERVER['PHP_SELF'] . '?&page=' . $previous . '">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a></li>';
    }
    if ($page < 3) {
        $next = $page + 1;
        echo '<li><li><a href="' . $_SERVER['PHP_SELF'] . '?&page=' . $next . '">
                                       <span aria-hidden="true">&raquo;</span>
                                   </a></li>';
    }
    ;

    echo '</ul></div></div></form>';
}
echo '</div></div></div>';
require ('template/footer.phtml');
