<?php require('template/header.phtml'); ?>

<input type="hidden" value="<?php echo $_SESSION['userID']; ?>" id="userID">
<input type="hidden" id="nrOfBooks" value="<?php echo $view->noOfBooks; ?>">
<div class="container">

    <div class="col-lg-offset-0">

        <div id="myList">

            <form action="<?php
            echo $_SERVER['PHP_SELF'];
            ?>" method="post">
                <?php
                if (empty($view->basket) and !(isset($_GET['thankYou']))) {
                    echo '<p id="thankYouMes" style="text-align: center; font-size: 20px;">
                            Your basket is empty. Feel free to <a style="color: #2b669a" href="../shopList.php">
                            <b>check</b></a> out our latest offers!
                          </p>';

                } else {

                    echo '

                        <nav class="nav navbar-fixed">

                        <div class="col-xs-12">
                            <button id="clearCart" class="clearCart btn btn-danger">Clear Cart</button>
                            <input id="checkOut" type="submit" class="btn btn-success pull-right" name="checkOut" value="CheckOut">

                        </div>
                        </nav>';

                    $totalPrice = 0; // variables for price
                    $finalPrice = 0;
                    foreach ($view->basket as $basketData) {

                        $basketBookId = $basketData->getBookID();
                        $book         = $view->booksDataSet->searchBook('idBook', $basketBookId);
                        $totalPrice += ($basketData->getQuantity() * $book->getPrice());
                        $finalPrice += $totalPrice;
                        echo '
                <div id="bookSet' . $basketData->getBookID() . '" class="bookSet col-sm-12" data-id="' . $basketData->getIdBasket() . '">
                        <p>' . '<img src="../images/' . $book->getPhotoName() . ' " alt="no pic" />' . '</p>
                        <p><b>Name:</b> ' . $book->getBookName() . ' </p>
                        <p><b>Available: </b>' . $book->getNumberInStock() . ' </p>
                        <b>Quantity</b><p class="itemQuantity' . $basketData->getBookID() . '">' . $basketData->getQuantity() . '</p>
                        <b>Price:</b><p class="priceForItem' . $basketData->getBookID() . '">' . money_format("%n",$book->getPrice()) . '</p>
                        <b>Total price: £</b><p class="totalPriceForItem">' .  money_format("%n", number_format($totalPrice,2)). '</p> 
                          <a class="btn btn-lg btn-primary" onclick=addCartPlus("' . $basketData->getBookID() . '")>
                            <em class="glyphicon glyphicon-plus-sign"></em></a>
                         
                          <a class="btn btn-lg btn-danger" onclick=removeFromCart("' . $basketData->getIdBasket() . '","'
                            . $basketData->getBookID(). '")><em class="glyphicon glyphicon-remove"></em></a>
                     
                          <a class="btn btn-lg btn-primary" onclick=removeFromCartMinus("'. $basketData->getIdBasket() .'","' .
                            $basketData->getBookID() . '","' . $basketData->getQuantity() . '")>
                <em class="glyphicon glyphicon-minus-sign"></em></a>
               
                        
                </div> ';
                    }
                }
                if (isset($_GET['thankYou'])) {

                    echo '<h3 class="text-center text-success">Thank you for shopping with us!</h3>';
                }

                ?>

            </form>
        </div>
    </div>
</div>