<?php require ('template/header.phtml')?>

<!DOCTYPE html>
<html>
<body>

<h2>Use the HTTP method POST to send data to the PHP file.</h2>


<button id="jsonBtn" onclick="json()" class="btn btn-success">Click</button>
<p id="demo"></p>

<!--<script>-->
<!--    // let obj, dbParam, xmlhttp, myObj, x, txt = "";-->
<!--    // obj = { "table":"customers", "limit":20 };-->
<!--    // dbParam = JSON.stringify(obj);-->
<!--    // xmlhttp = new XMLHttpRequest();-->
<!--    // xmlhttp.onreadystatechange = function() {-->
<!--    //     if (this.readyState == 4 && this.status == 200) {-->
<!--    //         myObj = this.responseText;-->
<!--    //         console.log(myObj);-->
<!--    //         // for (x in myObj) {-->
<!--    //         //     txt += myObj[x].name + "<br>";-->
<!--    //         // }-->
<!--    //         document.getElementById("demo").innerHTML = JSON.parse(myObj).table;-->
<!--    //     }-->
<!--    // };-->
<!--    // xmlhttp.open("POST", "my_parse_file.php", true);-->
<!--    // xmlhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");-->
<!--    // xmlhttp.send("x=" + dbParam);-->
<!---->
<!--</script>-->

<p>Try changing the "table" property from "customers" to "products".</p>

</body>
</html>



