<div id="response" style="font-size: 20px; width: 100%; position: fixed; margin-bottom: 15px;"  class="bg-success text-center text-success"></div>
<?php require('template/header.phtml'); ?>
<?php
    date_default_timezone_set('Europe/London');
   // $view->product = $_SESSION['book'];
?>
<body>
<div class="container" id="shop">

    <div class="row">
        <div class="col-sm-12" style="margin-top: 100px;">

            <div class="col-xs-11 col-sm-6">

                <?php
                echo '
                      <div href="product.php?id='. $view->product->getIdBook() .'"> 
                      <div id="output-box' .$view->product->getIdBook() .'"></div>
                       <div id="aloneBook">
                            <p style="font-size:15px;text-align: justify; margin-right: 20px; text-indent: 3em;"><img style="float:left;width:175px;height:250px;margin-right:15px;" 
                            src="/images/'. $view->product->getPhotoName()  . ' " 
                            alt="no pic" />
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet, nulla et dictum interdum, n
                            isi lorem egestas odio, vitae scelerisque enim ligula venenatis dolor.
                            Maecenas nisl est, ultrices nec congue eget, auctor vitae massa. Fusce luctus ve
                            stibulum augue ut aliquet. Mauris ante ligula, facilisis sed ornare eu, lobortis in odio.
                            Praesent convallis urna a lacus interdum ut hendrerit risus congue. Nunc sagittis dictum nisi,
                            sed ullamcorper ipsum dignissim ac. In at libero sed nunc venenatis imperdiet sed ornare 
                            turpis. Donec vitae dui eget tellus gravida venenatis. Integer fringilla congue eros non 
                            fermentum. Sed dapibus
                            pulvinar nibh tempor porta. Cras ac leo purus. Mauris quis diam velit.</span> 
                        </div>
                      </div>';
                ?>

            </div>
            <div style="font-size: 20px; padding-right: 30px;" class="col-xs-11 col-sm-6">
                <?php
                echo '<div href="product.php?id='. $view->product->getIdBook() .'"> 
                    <div id="singleBook">
                        <p style="font-size: 25px; color: #4876FF;"><b><i> ' . $view->product->getBookName() . ' 
                        </i></b>
                        </p>
                        <p><b>Author:</b> ' . $view->product->getAuthor() . ' </p>
                        <p><b>Available:</b> ' . $view->product->getNumberInStock() . ' </p>
                        <p><b>Price: £</b>'.$view->product->getPrice() . ' </p>
                    </div>
                    </div>';
                ?>

                <div class="w3-container w3-blue">
                    <h2>Quantity</h2>
                </div>
                <p id="quantityCheckMessage"></p>
                <p><input type="hidden" value=" <?php echo $view->product->getIdBook(); ?>" name="productID"></p>
                <p><input class="w3-card w3-input" type="number" id="quantityPerItem"
                          onkeyup="checkQuantity(this.min, this.max)" placeholder="Number of items..."
                          min="1" maxlength="100" max=" <?php echo $view->product->getNumberInStock() ?>"></p>
            </div>
        </div>
        <p><button class="btn-lg btn-success glyphicon-plus"
                   onclick="addMoreCart('<?php echo $view->product->getIdBook(); ?>')"
                   type="submit" name="addMoreItems"> Add to Basket </button></p>
    </div>
    <div id="displayBookMessage"></div>

    <div id="review-wrapper">
    <?php
    echo '
<form id="reviewForm" action="/product.php" method="post" class="w3-container w3-card-4 w3-light-grey w3-text-blue w3-margin">
<h2 class="w3-center">Contact Us</h2>

<div class="w3-row w3-section">
  <div class="w3-col" style="width:50px"><i class="w3-xxlarge fa fa-user"></i></div>
    <div class="w3-rest">
      <input class="w3-input w3-border" name="first" type="text" placeholder="First Name">
    </div>
</div>

<div class="w3-row w3-section">
  <div class="w3-col" style="width:50px"><i class="w3-xxlarge fa fa-pencil"></i></div>
    <div class="w3-rest">
      <input class="w3-input w3-border" name="message" type="text" placeholder="Message">
    </div>
</div>
 <button class="btn btn-success btn-lg" type="button" onclick="sendComment(
            this.form.id, ' . $view->product->getIdBook() . ')">Add Review</button>
</form>
        ';
    ?>
    </div>
<!--    <div style="margin-top: 100px;" id="demo"></div>-->
<!--    //id="loadBtn"-->
<!--    <button style="margin-bottom: 100px;" onclick="clickButton()">Click me!</button>-->

    <div id="print"></div>
    <div id="myBar"></div>
</div>





<div id="progress-box"></div>
<div style="text-align: center;">

    <button id="loadBtn" value="0" onclick="loadReviews(<?php echo $view->product->getIdBook(); ?>)"><a>
            Load Reviews</a></button>
</div>

</body>


<?php require('template/footer.phtml'); ?>
