
</div>
</div>
</body>
</html>
<footer id="myFooter">
    <div class="container">
        <div class="row">
            <div class="col-sm-4" style="text-align: center;">
                <h2 class="logo"><a href="#"> MyBooks </a></h2>
                <ul class="list-unstyled list-inline">
                    <li class="list-inline-item"><a class="btn-floating btn-sm btn-fb mx-1"><i style="font-size: 30px;" class="fa fa-facebook"> </i></a></li>
                    <li class="list-inline-item"><a class="btn-floating btn-sm btn-tw mx-1"><i style="font-size: 30px;" class="fa fa-twitter"> </i></a></li>
                </ul>
            </div>
            <div class="col-sm-2">
                <h5>Get started</h5>
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="../../register.php">Sign up</a></li>
                </ul>
            </div>
            <div class="col-sm-2">
                <h5>About us</h5>
                <ul>
                    <li><a href="#">Company Information</a></li>
                    <li><a href="#">Contact us</a></li>
                </ul>
            </div>
            <div class="col-sm-2">
                <h5>Support</h5>
                <ul>
                    <li><a href="#">FAQ</a></li>
                </ul>
            </div>
            <div class="col-sm-3">
                <button type="button" class="btn btn-danger">Contact us</button>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <p> <span class="glyphicon glyphicon-copyright-mark"></span> 2018 MyBooks</p>
    </div>
</footer>

<!--<div class="container-fluid">-->
<!--    <div class="footer">-->
<!---->
<!--        <p>Posted by: <a href="#">MyBooks</a></p>-->
<!--        <p>Contact information: <a href="mailto:m.r.blaga@edu.salford.ac.uk">Send E-mail</a>.</p>-->
<!--        <p>-->
<!--            <a href="#">-->
<!--                <span class="glyphicon glyphicon-copyright-mark"></span>-->
<!--            2016 MyBooks</a> &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms and Conditions</a>-->
<!--        </p>-->
<!--        <p class="pull-right"><a style="color: whitesmoke;" href="#"><b>Back to top<b></a></p>-->
<!--        </div>-->
<!---->
<!--    </div>-->
<!--</div>-->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<!--<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>-->
<!--<script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>-->

<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">-->
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">-->
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>-->
<!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>-->
<!--<script type="text/javascript" src="js/js.js"></script>-->


<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>-->
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>-->
<!--<script src="js/bootstrap.min.js"></script>-->
<!--<script src="js/js.js"></script>-->
<!--if (isset($view->errMessage)){-->
<!--//    echo "<script>-->
<!--//            $('#myModal').modal('show');-->
<!--//           </script>";-->
<!--//}-->
<!--//?>-->


