<footer id="myFooter">
    <div class="container">
        <div class="row">
            <div class="col-sm-4" style="text-align: center;">
                <h2 class="logo"><a href="#"> MyBooks </a></h2>
                <ul class="list-unstyled list-inline">
                    <li class="list-inline-item"><a class="btn-floating btn-sm btn-fb mx-1"><i style="font-size: 30px;" class="fa fa-facebook"> </i></a></li>
                    <li class="list-inline-item"><a class="btn-floating btn-sm btn-tw mx-1"><i style="font-size: 30px;" class="fa fa-twitter"> </i></a></li>
                </ul>
            </div>
            <div class="col-sm-2">
                <h5>Get started</h5>
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="../../register.php">Sign up</a></li>
                </ul>
            </div>
            <div class="col-sm-2">
                <h5>About us</h5>
                <ul>
                    <li><a href="#">Company Information</a></li>
                    <li><a href="#">Contact us</a></li>
                </ul>
            </div>
            <div class="col-sm-2">
                <h5>Support</h5>
                <ul>
                    <li><a href="#">FAQ</a></li>
                </ul>
            </div>
            <div class="col-sm-3">
                <button type="button" class="btn btn-danger">Contact us</button>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <p> <span class="glyphicon glyphicon-copyright-mark"></span> 2018 MyBooks</p>
    </div>
</footer>


