<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">                                                  <!-- HTML5 doc-type -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"">       <!--  responsive s-mobile -->
    <meta name="description" content="E-commerce website">
    <meta name="author" content="Mihai Raul, Blaga">

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/css/bootstrap-theme.css" rel="stylesheet">
    <link href="/css/my-style.css" rel="stylesheet">
    <link rel="icon" href="images/logo.png">
<!--    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">-->
<!--    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">-->
<!--    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>-->
<!--    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>-->


<!--    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>-->
<!--    <script src="js/jquery-1.11.0.min.js"></script>-->

<!--   next line used to define jquery for possible error line 6-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!--OKOKOKOKOKOKO-->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="../../js/js.js"></script>
    <script type="text/javascript" src="../../js/AjaxKitClass.js"></script>


    <title>MyBooks</title>
</head>

<body role="document">

<div class="navbar-wrapper">
    <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top">
        <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="../../index.php"><b><i>MyBooks</i></b></a>
        </div>
        <div id="myNavbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="../../shopList.php">Shop</a></li>
                <li onclick="search()"><a href="#searching">Search</a></li>
<!--                <li><a href="../../logOut.php"></a></li>-->
            </ul>

<!--            <form action="../../shopList.php" method="post" class="navbar-form navbar-left" role="search">-->
<!--                    <input name="search" type="text" class="form-control" placeholder="Search...">-->
<!--                <input name="look" type="submit" class="btn btn-primary" value="Search"  />-->
<!---->
<!--<!--                <div class='printchatbox' id='printchatbox'></div>-->
<!--<!---->
<!--<!--                <input type='text' name='fname' class='chatinput' id='chatinput'>-->
<!--            </form>-->
        <div id="refresh">
            <ul class="nav navbar-nav navbar-right">
                <?php

                if(isset($_SESSION['userID'])){

                   echo '<button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-user">
                            </span> ' . $_SESSION['userEmail'] . ' </button>
                        <ul class="dropdown-menu">
                            <li><a href="../../basket.php">My Basket</a></li>
                            <li><a href="../../logOut.php">LogOut</a></li>
                        </ul>
                        ';

                }
                else {

                   echo '<li><a href="../../register.php"><span class="glyphicon glyphicon-log-in"></span> LogIn/SignUp </a></li>';

                }
                ?>
            </ul>
            <div id="searching">
                <button type="button" class="close"><span class="glyphicon glyphicon-home"></button>
                <form id="searchForm" class="searchPageForm">
                    <input autocomplete="off" id="mySearch" name="q" onkeyup="showResult(this.value)" type="search" size="20" placeholder="start typing..."/>
                </form>
                <div class="custom-option" id="livesearch"">
            </div>
         </div>
         </div>
        </div>
        </nav>
    </div>
</div>

